USE [master]
GO


IF EXISTS (SELECT * FROM sys.sysdatabases WHERE NAME = '[ECENTRICDB]')
BEGIN 
ALTER database [ECENTRICDB] set offline with ROLLBACK IMMEDIATE;
DROP database  [ECENTRICDB];
END

CREATE DATABASE [ECENTRICDB] ON  PRIMARY 

( NAME = N'ECENTRICDB', FILENAME = N'E:\Apps\Metallix\DATA\ECENTRICDB.mdf' , SIZE = 5MB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ECENTRICDB_log', FILENAME = N'E:\Apps\Metallix\DATA\SECENTRICDB_Log.mdf' , SIZE = 5MB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ECENTRICDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECENTRICDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECENTRICDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECENTRICDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECENTRICDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECENTRICDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECENTRICDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECENTRICDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECENTRICDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ECENTRICDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECENTRICDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECENTRICDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECENTRICDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECENTRICDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECENTRICDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECENTRICDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECENTRICDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECENTRICDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECENTRICDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECENTRICDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECENTRICDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECENTRICDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECENTRICDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECENTRICDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECENTRICDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECENTRICDB] SET  READ_WRITE 
GO

ALTER DATABASE [ECENTRICDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ECENTRICDB] SET  MULTI_USER 
GO

ALTER DATABASE [ECENTRICDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECENTRICDB] SET DB_CHAINING OFF 
GO

USE [ECENTRICDB]
GO

/****** Object:  Table [dbo].[CostCentre]    Script Date: 05-04-2019 12:31:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CostCentre](
	[costcentreID] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[accountNO] [varchar](50) NULL,
 CONSTRAINT [PK_CostCentre] PRIMARY KEY CLUSTERED 
(
	[costcentreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [ECENTRICDB]
GO

/****** Object:  Table [dbo].[Department]    Script Date: 05-04-2019 12:31:44 PM ******/
USE [ECENTRICDB]
GO

/****** Object:  Table [dbo].[Department]    Script Date: 05-04-2019 12:31:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Department](
	[DepartmentID] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[costCentreID] [int] NOT NULL,
 CONSTRAINT [PK_Department] PRIMARY KEY CLUSTERED 
(
	[DepartmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Department]  WITH CHECK ADD  CONSTRAINT [FK_Department_CostCentre] FOREIGN KEY([costCentreID])
REFERENCES [dbo].[CostCentre] ([costcentreID])
GO

ALTER TABLE [dbo].[Department] CHECK CONSTRAINT [FK_Department_CostCentre]
GO

USE [ECENTRICDB]
GO

/****** Object:  Table [dbo].[SalaryLevel]    Script Date: 05-04-2019 12:32:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SalaryLevel](
	[salaryLevelID] [int] IDENTITY(1,1) NOT NULL,
	[amount] [decimal](7, 2) NULL,
	[increasePercentage] [smallint] NULL,
 CONSTRAINT [PK_SalaryLevel] PRIMARY KEY CLUSTERED 
(
	[salaryLevelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO














